# Generated by Django 5.2.17 on 2026-09-23 06:43

import apps.volume_price_merge.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumePriceMergeJob',
            fields=[
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='volume_price_merge', serialize=False, to='jobs.job')),
                ('pairing_preview', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='MergeInputFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('production', '產量及產值'), ('area', '種植及收穫面積')], max_length=16)),
                ('major_category', models.CharField(max_length=100)),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(max_length=500, upload_to=apps.volume_price_merge.models.merge_input_path)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merge_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_files', to='volume_price_merge.volumepricemergejob')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('merge_job', 'property_type', 'major_category'), name='uq_merge_file_role_category')],
            },
        ),
    ]
